all:
	clang++ -Wall -Wextra -Werror Response.cpp ft_utils.cpp main.cpp ../config/ConfigParse.cpp ../parser/RequestParser.cpp ../parser/PathParser.cpp ../parser/Utils.cpp ../exception/Exception.cpp
	./a.out
